### ISSUE TITLE
Feature: convention or config option to specify error page

### ISSUE THREAD

**Issue by ElementML** [geelen/react-snapshot#10]
Thank you for your work on this @geelen - I've been banging my head against the wall for a week trying to pre-render my very simple React site for static hosting. After numerous fruitless attempts with server-rendering, server-side webpack bundles and various static site generators, this lib is an absolute breath of fresh air. I'm not using create-react-app, and react-snapshot worked for me pretty much "out of the box" - I only needed to send my build output to build/ rather than dist/. 

The only gotcha I ran into was trying to snapshot an error page to serve for 404s. I use react-router, and have a catch-all route configured. This works fine once client-side routing kicks in, but I still need to pre-render an error page to serve to users with JS disabled. The problem is the route is unreachable by crawling relative links from the entry point. As a workaround, I'm including a link to /error in my root route and hiding it with CSS. 

Any of the following would be welcome features:
- A convention for crawling error pages (crawler hits /error or some other standard location)
- A configuration option for specifying an error page or other locations unreachable by crawling
- For react-router users, an option to tell the crawler to traverse the route tree

I'll try to hack something together and will open a PR if I get anywhere with any of the above, but documenting this in the meantime in case someone else gets to it first.

**Comment by geelen** [comment]
I think #12 should solve this actually. You can put `/error` in as config and it'll get crawled like normal.
