### ISSUE TITLE
Doesn't work for dynamic redirects

### ISSUE THREAD

**Issue by scratchyone** [geelen/react-snapshot#106]
If you have dynamically generated redirects, react-snapshot doesn't know.
I have code like this as my only way of getting around the site. You click a button, it checks some information, and then adds a redirect tag. 
`if (!doc.authorized) {
  this.setState({ redirect: <Redirect to="/" /> });
}
`

**Comment by scratchyone** [comment]
You could maybe crawl src/index.js and look for redirect and link tags and crawl that.

**Comment by FelixKuehl** [comment]
Or you just force the rendering of this page in your reactSnapshot config in your package.json
```json
"reactSnapshot": {
    "include": [
      "/foo"
    ]
  }
```
