### ISSUE TITLE
`react-helmet` v5 no longer works with `react-snapshot`

### ISSUE THREAD

**Issue by haroldhues** [geelen/react-snapshot#17]
**Setup**: [Follow this tutorial](https://medium.com/superhighfives/an-almost-static-stack-6df0a2791319) to setup an app with `react-helmet` version 5 or greater.

**Expected**: The snapshot contains a title (or other metadata) specified in a `<Helmet>`

**Actual**: The snapshot contains the head from the `index.html` template without the proper title, etc.

https://github.com/nfl/react-helmet/commit/0ad790830a1121b6c645f4f9a678a60fc604cf94 is the breaking commit in `react-helmet`. It looks like they started batching updates to the dom for better performance. My guess is that the snapshot is taken before the callback is triggered to update the title now.

If this seems like this is the correct place to fix the issue I would be happy to investigate a fix/pr.

**Comment by geelen** [comment]
Hmm... that's annoying. I suppose I could use `requestIdleCallback` as well, to make sure the snapshot is taken later?

**Comment by haroldhues** [comment]
It looks like `requestIdleCallback` doesn't exist in JSDOM. In that case, helmet should fall back to using `setTimeout` with a timeout of 1. Perhaps just delaying the snapshot using `setTimeout` with a large timeout like 100 milliseconds would be a simple enough? It would slow things down, but maybe crawling pages in parallel in the future could compensate for the delay?
