### ISSUE TITLE
Build not working when opening the page manually.

### ISSUE THREAD

**Issue by MichhDiego** [geelen/react-snapshot#25]
When opening the `index.html` file by doing `right click` -> `open with ....`. 
I receive the following error: 

`main.0ea4972e.css Failed to load resource: net::ERR_FILE_NOT_FOUND`
`main.202c8226.js Failed to load resource: net::ERR_FILE_NOT_FOUND`

I went to the builded `index.html` file where I see that `index.html` is trying to import the files from `/static/css/` instead of `static/css/`, see here:

```
<link href="/static/css/main.0ea4972e.css" rel="stylesheet">
<script type="text/javascript" src="/static/js/main.202c8226.js"></script>
```

If I replace this to: 
```
<link href="static/css/main.0ea4972e.css" rel="stylesheet">
<script type="text/javascript" src="static/js/main.202c8226.js"></script>
```
It works!

**Comment by geelen** [comment]
Not sure about the second, but the first is definitely because you're opening it as a file rather than through a web server. You can use https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb?hl=en or https://anvilformac.com/ or just a command line web server like https://www.npmjs.com/package/http-server

Fire it up and see if the second problem goes away too?

**Comment by MichhDiego** [comment]
@geelen I am sorry I added 2 questions that I think now are unrelated in the same issue, my bad. I just moved the second question to a new issue (#28), and removed it from the description.

Regarding your answer, thanks! That solves the problem for sure! But I am looking for a way of opening it as a file, do you think its possible? For now I can fix the problem by removing the `/` at the beginning.

**Comment by kantenkugel** [comment]
While this might be possible (programatically replacing the url at snapshot-time), i think it is unwanted, as this would just replace the injection generated by create-react-app and doesn't really have to do with the static rendering part that react-snapshot does. The pages aren't meant to be opened as files anyway. 

You can just use the serve package like described in the [create-react-app readme](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#static-server)

**Comment by MichhDiego** [comment]
@kantenkugel @geelen Great answers, thank you very much guys. I actually found out a way of using it like this, the problem had to do with my FTP configuration and not react-snapshot itself.

I am closing the issue as its solved!
