### ISSUE TITLE
Would like to render asynchronously, is this possible?

### ISSUE THREAD

**Issue by kristojorg** [geelen/react-snapshot#32]
I have a site that does data fetching via `apollo-graphql`, and I would like to pre-render it as a static site. Do you know how I can configure this to await the incoming data while generating html?

**Comment by fredrik-sogaard** [comment]
Check out the async branch!

**Comment by auser** [comment]
I'm a tad confused about how to handle this with `react-apollo`. I think the `.rendering(Component)` is throwing me off. Using something like `recompose`, my current implementation looks like the following:

```javascript
const Home = ({ query }) => <div>{query.name}</div>

const data = graphql(
  gql`
    {
      allPosts {
        id
        name
      }
    }
  `,
  {
    name: 'query'
  }
);

const Loading = () => <div>Loading...</div>;

const withLoading = branch(
  (props: any) => props.query.loading,
  renderComponent(Loading)
);

const ComponentWithSnapshot = Snapshot({
  query: (props: any) => Promise.resolve(props.query)
}).rendering(Home);

const ComposedHome = compose(data, withLoading)(ComponentWithSnapshot);

export default ComposedHome;
```

Yet, even with searching through the source, I'm hitting an error while building. Curious if anything looks wrong on first glance here for you...

The error I'm hitting is:

```bash
TypeError: Cannot read property '_location' of null
    at Window.get location [as location]
```

**Comment by avkonst** [comment]
Hit the same problem. I have got markdown files loaded into react components. Snapshoted HTML pages contain 'Loading...' because the content of markdown is fetched asynchronously and 'Loading...' is replaced with real content later. 

You are mentioning async branch. Where is it? How can it be used? Will it be merged to master?

**Comment by avkonst** [comment]
OK. I have found. async-16 branch works. When are you planning to release 2.x version?

**Comment by zomars** [comment]
@avkonst care to share your setup?

**Comment by avkonst** [comment]
@zomars sorry missed your question . I actually do not have the setup because I stopped using this project.
