### ISSUE TITLE
Support to save crawled page as `/path/index.html`

### ISSUE THREAD

**Issue by PoiScript** [geelen/react-snapshot#35]
Some server, for example SimpleHTTPServer for Python, don't redirect `/path` to `path.html`. It failed when I visited `/path` directly.After moving all `path.html` to `/path/index.html`, everything works fine.

Could you please add a feature that would allow us to control the location of saving? This won't be hard, I think, just add a few lines in [`Writer.js`](https://github.com/geelen/react-snapshot/blob/master/src/Writer.js) & [`cli.js`](https://github.com/geelen/react-snapshot/blob/master/src/cli.js).

**Comment by PoiScript** [comment]
I had sent a pull request #36, it just checks for the flag '--save-as-index-html' and then changes the filenames. You should change '--save-as-index-html' to anything else, bacause I'm not good at naming...

**Comment by angusfretwell** [comment]
This will enable deployment to S3 (an a lot of other service, no doubt)

**Comment by Jinksi** [comment]
I just accidentally discovered that this feature already exists, if you setup each `<Link />` to end with a trailing `/`.
https://github.com/geelen/react-snapshot/blob/master/src/cli.js#L36-L37
Your solution does force `/path/index.html` which may be useful.
However in my case I wanted both `/pathA.html` and `/pathB/index.html`, so I found the existing functionality works for me.

**Comment by PoiScript** [comment]
Sorry for the delay.
@angusfretwell yes, I know that the hosting service can do the redirect job but I still want this feature because the common filename is `/path/index.html` rather than `/path.html`.
Thank to @Jinksi, you are right! I had already realized that an addition `/` might work but I was doing the wrong way by adding it to `<Route />`... :(
Thank you guys, I'm closing this issue and the related PR.
