### ISSUE TITLE
It would be better if the build folder could be customized.

### ISSUE THREAD

**Issue by leadream** [geelen/react-snapshot#42]
Hi, Geelen, first of all thanks for your great job. I'm using react-snapshot in my project now, but I encountered a problem. Our website is an international site so I need to globalize it when generating static pages. My idea is to generate several build folders for different areas, such as `build` for English speaking area, `build-cn` for Chinese speaking area, etc.

When I look into the code, I found that the build folder is fixed into the code. I think we can add parameter in the cli command to determine the destination to build. The command looks like:
```sh
react-snapshot --dist build-cn
```
If possible I will make a PR.

**Comment by geelen** [comment]
On this now

**Comment by geelen** [comment]
Fixed and released as `1.3.0` 👌

**Comment by Kefir100** [comment]
Hi, I have encountered the same problem. Unfortunately, I could not find a solution in the docs. Had to find the issue manually) Any plans about updating the docs?

**Comment by kelseygasser** [comment]
@Kefir100 how did you fix the issue?

**Comment by Kefir100** [comment]
@kelseygasser 
```javascript
.option('--build-dir <directory>', `Specify where the JS app lives. Defaults to 'build'`)
.option('--domain <domain>', `The local domain to use for scraping. Defaults to 'localhost'`)
.option('--output-dir <directory>', `Where to write the snapshots. Defaults to in-place (i.e. same as build-dir)`)
```

using command line interface, you can easily specify the build directory
```
react-snapshot --build-dir path/to/build_dir
```
