### ISSUE TITLE
I followed the guide, it created a 200.html but is it working? (question)

### ISSUE THREAD

**Issue by jasan-s** [geelen/react-snapshot#49]
After following the instructions in read me section: **"The How To"** , I get a an extra 200.html file in build directory however I am unclear as to if its working.  Is there something extra i need to do? Additionally, If i use something like react-router would I just add the paths that I want react-snapshot to create static files for in the "include" but if I don't add anything in "exclude" would react-snapshot ignore all others paths? or do i need to specify which paths to ignore(exclude) exactly?

**Comment by geelen** [comment]
No it should crawl every route it finds on the page, unless they match what's in `exclude`. If you look at your `200.html` vs the new `index.html`, you should see the difference (`200` should have an empty `<body>` tag except for the react root, whereas `index` has the rendered output of your app).
