### ISSUE TITLE
static markup for a protected secure path

### ISSUE THREAD

**Issue by jasan-s** [geelen/react-snapshot#51]
I have a protected route that is allowed once user is logged in. i.e : `path='/user/:id'`
Is it possible to generate static markup for this path at runtime using this lib?  i tired using 
``` 
 "reactSnapshot": {   
     "include": [
        "/",
       "/user/**"]
   }

that leads to error:  `No such filr or directory`

**Comment by stereobooster** [comment]
it should be actual urls, not wildcards

**Comment by jasan-s** [comment]
@stereobooster it wouldn't work for say "/user/:id"

**Comment by stereobooster** [comment]
I suppose the only thing you can do here is to create dedicated shell page and prerender it.

**Comment by jasan-s** [comment]
yeah that is always a option, but that would require me to manually generate a sttaic page and save it to the build everytime there is a chnage to private route.

**Comment by stereobooster** [comment]
you do not need SEO/SMO for private pages, so you can refuse from prerendering. If you care about load performance - private page can not be visited without visiting public page first (login), where you can install serviceworker with the shell provided.

**Comment by jasan-s** [comment]
yeah it was mostly for the performance I wanted the pre-render for private page.  quick followup: I'm using `create-react-app` and i'm registering service worker in my `index.js` is that enough? or do I need to do anything else for the service worker to cache the static html for the private route?

**Comment by stereobooster** [comment]
by default it caches only `*.js`, `*.css` and `index.html`. It can happen that you need adapt it a bit https://github.com/stereobooster/react-snap/blob/master/Recipes.md#configure-sw-precache-without-ejecting

**Comment by jasan-s** [comment]
thanks for that @stereobooster. so how is  `build/shell.html`  generated to the build directory , If `react-snap` is not used?

**Comment by stereobooster** [comment]
in case if you do not use prerenderer `index.html` serves as shell. If you use prerenderer you can create dedicated page (`/shell`) and add it to `include` config.

**Comment by jasan-s** [comment]
cool, thanks.
