### ISSUE TITLE
Pre-rendered static markup using create-react-app not being served correctly

### ISSUE THREAD

**Issue by jasan-s** [geelen/react-snapshot#52]
I successfully can generate static files at build for the routes: ` "/"`,` "/signIn"`,` "/signUp" `respectively: `index.html`,` signIn.html`, `signUp.html`.

When I launch my local server to run the app, the app succesfully loads the static index.html for the root route `"/"` , however the issue is If I go to any subroute such as `"/signIn"` or `"/signUp"` , the app renders the same `index.html` static file from rootpath and then immediately serves the correct components using `main.js`.

Checking the View page source for the sub routes, I have confirmed the `index.html` markup for the homepage is being served. Additionally I checked network traffic, and it seems the static document for the subroutes is being served from Service Worker. Not sure if that is the problem.
Also posted the issue on [Stackoverflow](https://stackoverflow.com/questions/45775914/): 

code in package.json:

```
  "reactSnapshot": {
    "include": [
      "/",
      "/signIn",
      "/signUp"
    ],
    "exclude": [],
    "snapshotDelay": 300
  }
```

**Comment by jasan-s** [comment]
This error may be due to create react app serving static document from service worker. but not sure

**Comment by julianhandl** [comment]
@jasan-s Hey. Have you found a solution for this problem?

**Comment by jasan-s** [comment]
@julianhandl  yes I did. I answered it [here](https://stackoverflow.com/questions/46213861/):
