### ISSUE TITLE
Reconsider using emojis in console output

### ISSUE THREAD

**Issue by martinandert** [geelen/react-snapshot#6]
In my terminal it looks like this:

![terminal](https://cloud.githubusercontent.com/assets/6715978/18354241/1d1d5096-75e5-11e6-8e50-f1c62ff324b0.png)

And in my editor (Sublime Text):

![editor](https://cloud.githubusercontent.com/assets/6715978/18354253/2a62f1ca-75e5-11e6-9b0a-acee8f2ab4c7.png)

**Comment by geelen** [comment]
Weird! I've seen emojis fail silently before but never fall back to... whatever that is. Those are the hex codes of 🕷 and 🕸 too. What terminal/font/OS is that?

Maybe I can detect it and output something different? Because I 😍 emoji.

**Comment by martinandert** [comment]
> What terminal/font/OS is that?

It's gnome-terminal of latest Linux Mint with Monaco font. The editor uses Source Code Pro as font.

**Comment by MoOx** [comment]
I think Linux does not provides a set of emojis. A friend told me this.

**Comment by martinandert** [comment]
> I think Linux does not provides a set of emojis.

So maybe use [Node.js' process.plaform](https://nodejs.org/api/process.html#process_process_platform) then?

**Comment by geelen** [comment]
Sorry about this, but I'm going to close this issue. I'd happily merge a PR to do this but I'm short on time to implement this myself and surely Linux will get emojis eventually so this problem may go away!
