### ISSUE TITLE
Generate 404.html

### ISSUE THREAD

**Issue by stereobooster** [geelen/react-snapshot#67]
Generate 404.html in the manner of 200.html

**Comment by Jinksi** [comment]
Try adding the following to your `package.json` to crawl `/404.html`:
```
"reactSnapshot": {
    "include": [
      "/404"
    ]
  }
```

**Comment by stereobooster** [comment]
Genius. I suppose we need to document all that small bits, which are useful for deployment to S3. Like this one or to use slash in the end of the link to produce `path/index.html`
