### ISSUE TITLE
Dynamic routes

### ISSUE THREAD

**Issue by urre** [geelen/react-snapshot#73]
Looked at some examples and pre defined routes like `/about` seems to work fine, but does this work for dynamic routes aswell like `/:pageid`. How should i set it up then?

**Comment by linonetwo** [comment]
Seems not working correctly, other page will fresh before dynamic route loads

**Comment by jasan-s** [comment]
can't seems to figure out how to use it with dynamic routes or with `redux-persist` successfully.

**Comment by stereobooster** [comment]
React-snapshot will crawl all links that it will found. You can create "site map" page, which will contain links to all pages.

**Comment by aaronshaf** [comment]
@stereobooster That's a great idea! I recommend adding that tip to the documentation.

**Comment by geelen** [comment]
Closed in #81 thanks @aaronshaf
