### ISSUE TITLE
Different 'build' path

### ISSUE THREAD

**Issue by georgest** [geelen/react-snapshot#78]
What happens when you have different `build` path.
For example my build folder is in `./web/build`.

When I run react-snapshot it doesn't not render anything. The console output is:
`🕷   Starting crawling http://localhost:59703/`
`🔥 'render' from react-snapshot was never called. Did you replace the call to ReactDOM.render()?`
`🕸   Finished crawling.`

**Comment by stereobooster** [comment]
duplicate of https://github.com/geelen/react-snapshot/issues/42
