### ISSUE TITLE
How can I render Route with URL parameters ?

### ISSUE THREAD

**Issue by rhtm123** [geelen/react-snapshot#94]
How can I render route like this-
`<Route path='/subject/:subjectSlug/:subjectID' component={CourseList}/>`

**Comment by stereobooster** [comment]
Add `<Link to="/subject/test/1">first subject</Link>` somewhere in your application and it will render `/subject/test/1.html`. Add links to all your subjects and you're done.

**Comment by rhtm123** [comment]
Can I create a single HTML page for all my courses?

**Comment by stereobooster** [comment]
Yes sure. From readme:

> React-snapshot will crawl all links that it finds. You can create "site map" page, which will contain links to all pages.

**Comment by stereobooster** [comment]
@rhtm123 Can you please close this issue if it is solved for you. Thanks
